on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Build distributions
        run: uv build

      - name: Check distributions
        run: uv run --with twine twine check dist/*

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: dist/

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/remus

    permissions:
      id-token: write

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false

      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/

      - name: Publish package
        run: uv publish
